// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxNlwjpmuhE6wcOnnneK9CE2J8BmnszPI',
    appId: '1:403788255136:web:1dca1f17da094c57c79ec5',
    messagingSenderId: '403788255136',
    projectId: 'student-accomodation-portal',
    authDomain: 'student-accomodation-portal.firebaseapp.com',
    storageBucket: 'student-accomodation-portal.appspot.com',
    measurementId: 'G-C5RPJNTF47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB96xmO9NmhVqGzUOzMtzlo6yL0HLBy_lg',
    appId: '1:403788255136:android:e89b40e5719311afc79ec5',
    messagingSenderId: '403788255136',
    projectId: 'student-accomodation-portal',
    storageBucket: 'student-accomodation-portal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzsDBAc5NcKl9Zlc-TgapmCkmG3tgFEcQ',
    appId: '1:403788255136:ios:3b1ac68a31185bd4c79ec5',
    messagingSenderId: '403788255136',
    projectId: 'student-accomodation-portal',
    storageBucket: 'student-accomodation-portal.appspot.com',
    iosBundleId: 'com.example.flutterEcommerceTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzsDBAc5NcKl9Zlc-TgapmCkmG3tgFEcQ',
    appId: '1:403788255136:ios:7a44096bf8bb7808c79ec5',
    messagingSenderId: '403788255136',
    projectId: 'student-accomodation-portal',
    storageBucket: 'student-accomodation-portal.appspot.com',
    iosBundleId: 'com.int2.flutterEcommerceTemplate',
  );
}
